id: I1727C96B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:19:22+00:00'
last_modified: '2022-06-07T20:31:06.415521+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25823
  title: ཚན་རིག་པའི་བྱུང་བ་བརྗོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    3E8E:
      image_group_id: I1KG25825
      title: ''
      total_pages: 142
      order: 1
      base_file: 3E8E.txt
    70E1:
      image_group_id: I1KG25826
      title: ''
      total_pages: 146
      order: 2
      base_file: 70E1.txt
    D1DE:
      image_group_id: I1KG25827
      title: ''
      total_pages: 155
      order: 3
      base_file: D1DE.txt
    146D:
      image_group_id: I1KG25828
      title: ''
      total_pages: 148
      order: 4
      base_file: 146D.txt
    '9008':
      image_group_id: I1KG25829
      title: ''
      total_pages: 141
      order: 5
      base_file: 9008.txt
    8B1F:
      image_group_id: I1KG25830
      title: ''
      total_pages: 136
      order: 6
      base_file: 8B1F.txt
    DA5A:
      image_group_id: I1KG25831
      title: ''
      total_pages: 140
      order: 7
      base_file: DA5A.txt
    11BA:
      image_group_id: I1KG25832
      title: ''
      total_pages: 124
      order: 8
      base_file: 11BA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
